// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibrarySystem.Data.Models
{
    [Table("books_customers_loan")]
    public partial class BooksCustomersLoan
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("book_id")]
        public int? BookId { get; set; }
        [Column("customer_id")]
        public int? CustomerId { get; set; }
        [Column("loan_date", TypeName = "datetime")]
        public DateTime? LoanDate { get; set; }
        [Column("delivery_date", TypeName = "datetime")]
        public DateTime? DeliveryDate { get; set; }
        [Column("delivered_date")]
        public bool? DeliveredDate { get; set; }

        [ForeignKey("BookId")]
        [InverseProperty("BooksCustomersLoans")]
        public virtual Book Book { get; set; }
        [ForeignKey("CustomerId")]
        [InverseProperty("BooksCustomersLoans")]
        public virtual Customer Customer { get; set; }
    }
}