// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibrarySystem.Data.Models
{
    [Table("books")]
    public partial class Book
    {
        public Book()
        {
            BooksLoans = new HashSet<BooksLoan>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("Nome")]
        public string Name { get; set; }
        [Required]
        [Column("author")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("Autor")]
        public string Author { get; set; }
        [Required]
        [Column("publisher")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("Editora")]
        public string Publisher { get; set; }
        [Column("publication_date", TypeName = "date")]
		[DataType(DataType.Date)]
        [DisplayName("Data de Publicação")]
        public DateTime PublicationDate { get; set; }
        [Column("edition")]
        [StringLength(50)]
        [Unicode(false)]
        [DisplayName("Edição")]
        public string Edition { get; set; }

        [InverseProperty("Book")]
        public virtual ICollection<BooksLoan> BooksLoans { get; set; }
    }
}