// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibrarySystem.Data.Models
{
    [Table("books")]
    public partial class Book
    {
        public Book()
        {
            BooksCustomersLoans = new HashSet<BooksCustomersLoan>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("author")]
        [StringLength(100)]
        [Unicode(false)]
        public string Author { get; set; }
        [Required]
        [Column("publisher")]
        [StringLength(100)]
        [Unicode(false)]
        public string Publisher { get; set; }
        [Column("publication_year", TypeName = "datetime")]
        public DateTime PublicationYear { get; set; }
        [Column("edition")]
        [StringLength(50)]
        [Unicode(false)]
        public string Edition { get; set; }

        [InverseProperty("Book")]
        public virtual ICollection<BooksCustomersLoan> BooksCustomersLoans { get; set; }
    }
}