// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LibrarySystem.Data.Models
{
    public partial class LibrarySystemContext : DbContext
    {
        public LibrarySystemContext()
        {
        }

        public LibrarySystemContext(DbContextOptions<LibrarySystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BooksCustomersLoan> BooksCustomersLoans { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-VTMOVEN;Initial Catalog=library_db;User ID=sa;Password=1234; TrustServerCertificate=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BooksCustomersLoan>(entity =>
            {
                entity.HasOne(d => d.Book)
                    .WithMany(p => p.BooksCustomersLoans)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK_books_customers_loan_books");

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.BooksCustomersLoans)
                    .HasForeignKey(d => d.CustomerId)
                    .HasConstraintName("FK_books_customers_loan_customers");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}